### PR TITLE
[MOD] Added support for net6.0 target framework

### PR DESCRIPTION
**Pull request by boyko-ant**

### CODE REVIEW

**Comment by proudmonkey** [comment]
Hey Thank you for your PR. Been super busy lately.  I truly appteciate your contribution.. I was working with code refactoring in the branch v.5-beta. Can you make your changes based on that please instead of master? 

Thank you again.

**Comment by boyko-ant** [comment]
Hi!
I've created a new pull request, as you asked (#144).
But I would like to ask you to review and merge this one as well. One of my current projects can really benefit from your library being upgraded to .NET 6. We will be even more excited to upgrade from version 4.5 to version 5.0, but the absence of NET 6 support is something that impacts us quite hard.

**Review by proudmonkey — APPROVED** [review]
Looks good. Thanks for your contribution.

**Comment by proudmonkey** [comment]
@boyko-ant `v4.5.1` has been released to support .NET 6.

See: https://www.nuget.org/packages/AutoWrapper.Core/4.5.1

Thank you.

**Comment by boyko-ant** [comment]
That is exactly what I was looking for, thanks!

**Pull request merged**
