### PR TITLE
Update ApiProblemDetails.cs

### PR DESCRIPTION
**Pull request by EmreMengukan**
internal class to public
Method attribute swagger support
[ProducesResponseType(typeof(ApiProblemDetails), Status422UnprocessableEntity)]

### CODE REVIEW

**Comment by proudmonkey** [comment]
@EmreMengukan AutoWrapper provides public Models that you can use as type for responses here: https://github.com/proudmonkey/AutoWrapper/tree/master/src/AutoWrapper/Models

**Comment by EmreMengukan** [comment]
Super :)
I have done it using as below

```
[ProducesResponseType(typeof(ApiResultResponse<TestResponse>), Status200OK)]
[ProducesResponseType(typeof(ApiProblemDetailsValidationErrorResponse), Status422UnprocessableEntity)]
[ProducesResponseType(typeof(ApiProblemDetailsExceptionResponse), StatusCodes.Status500InternalServerError)]
```

```
public class TestResponse
{
    public string Name { get; set; }
}
```

ApiResultResponse.cs file properties **StatusCode** column not found. should i use this with new ApiResultClass with PropertyAttribute [AutoWrapperPropertyMap(Prop.StatusCode)]

AutoWrapper.Wrappers.ApiResponse it's in it **StatusCode**

**Comment by proudmonkey** [comment]
It was my intent not to include StatusCode in the response body as it appears redundant.

**Comment by EmreMengukan** [comment]
> It was my intent not to include StatusCode in the response body as it appears redundant.

thank you for your return

**Pull request closed without merging**
